#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Netresearch DTT GmbH
#
# hardening-check.sh — fail CI when an overlay introduces a long-running
# service without the stack's container-hardening posture.
#
# Why this exists:
#   PR #21's audit caught that the new Bugsink overlay services shipped
#   without security_opt + cap_drop, because compose anchors (x-logging,
#   x-app-env) don't survive across overlay files. Every long-running
#   service in compose.yml uses
#     security_opt: [no-new-privileges:true]
#     cap_drop:     [ALL]
#   and overlays must keep that posture for services they introduce.
#
# Scope (intentional):
#   * Only services an overlay INTRODUCES (present in the merged config,
#     absent from the base-only config) are checked. Services the overlay
#     merely modifies (e.g. compose.traefik.yml only adjusts `web`) are
#     ignored — that path goes through the base compose.yml lint.
#   * One-shot init containers (restart: "no") are excluded — they run
#     once to completion, so the long-running-container threat model
#     (privilege-escalation in a persistent process) doesn't apply.
#   * Out of scope: an overlay clobbering inherited hardening on a base
#     service (e.g. `cap_drop: !reset []` on web). Not the original
#     incident; add a separate rule if that becomes a real risk.
#
# Usage:
#   tests/lint/hardening-check.sh            # check all examples/compose.*.yml
#   tests/lint/hardening-check.sh path.yml … # check the named overlay(s)
#
# Requirements:
#   docker (compose v2)  — to merge base + overlay
#   yq (mikefarah)       — to query the merged YAML
#
# Exits 0 on success, 1 on any offender, 2 on tool/setup errors.

set -euo pipefail

# Resolve repo root from this script's location (tests/lint/<this>).
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
REPO_ROOT=$(cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd)

BASE_COMPOSE="${REPO_ROOT}/compose.yml"
if [[ ! -f "${BASE_COMPOSE}" ]]; then
  echo "error: base compose file not found at ${BASE_COMPOSE}" >&2
  exit 2
fi

for tool in docker yq; do
  if ! command -v "${tool}" >/dev/null 2>&1; then
    echo "error: '${tool}' is required but not on PATH" >&2
    exit 2
  fi
done

# Pick overlays to check.
if (( $# > 0 )); then
  overlays=("$@")
else
  # globbing is the intended mechanism here; if no files match we exit 0.
  shopt -s nullglob
  overlays=("${REPO_ROOT}"/examples/compose.*.yml)
  shopt -u nullglob
fi

if (( ${#overlays[@]} == 0 )); then
  echo "no overlays found under examples/ — nothing to check"
  exit 0
fi

# Build the env-file. Every ${VAR:?...} reference across the base + overlays
# needs a value or `docker compose config` rejects the merge. Generate a
# throwaway file under TMPDIR so we never write into the working tree.
# `mktemp -t` is not portable between GNU and BSD/macOS — use a full
# template instead so the script runs the same on both.
ENV_FILE=$(mktemp "${TMPDIR:-/tmp}/hardening-check-env.XXXXXX")
trap 'rm -f "${ENV_FILE}"' EXIT

cat > "${ENV_FILE}" <<'EOF'
# Auto-generated by tests/lint/hardening-check.sh — throwaway values for
# `docker compose config` validation only. NEVER use these at runtime.
APP_KEY=base64:LINT_PLACEHOLDER_KEY_NOT_FOR_RUNTIME_USE_ONLY=====
DB_PASSWORD=lint-dummy
DB_ROOT_PASSWORD=lint-dummy
BUGSINK_SECRET_KEY=lint-dummy
BUGSINK_ADMIN_EMAIL=lint@example.invalid
BUGSINK_ADMIN_PASSWORD=lint-dummy
EOF

# yq filter: emit one TSV row per service:
#   <name> <TAB> <restart> <TAB> <has_no_new_privileges> <TAB> <has_cap_drop_ALL>
# `// []` normalises both "absent" and "null" into an empty list, and yq
# treats `cap_drop: [ALL]` (flow) and a block list identically once parsed.
# shellcheck disable=SC2016  # yq expression — must NOT be expanded by bash
SERVICE_REPORT_YQ='
  .services
  | to_entries
  | map(. as $s | {
      "name": $s.key,
      "restart": ($s.value.restart // "unless-stopped"),
      "has_nnp": (($s.value.security_opt // []) | map(. == "no-new-privileges:true") | any),
      "has_capdrop_all": (($s.value.cap_drop // []) | map(. == "ALL") | any)
    })
  | .[]
  | [.name, .restart, (.has_nnp|tostring), (.has_capdrop_all|tostring)]
  | @tsv
'

# Helper: run `docker compose ... config` and emit the per-service TSV.
# Stderr is suppressed on success; on failure we re-run with stderr visible
# so the operator gets the real error.
service_report() {
  local -a files=()
  for f in "$@"; do
    files+=(-f "${f}")
  done
  if ! docker compose --env-file "${ENV_FILE}" "${files[@]}" config 2>/dev/null \
      | yq -r "${SERVICE_REPORT_YQ}"; then
    echo "error: failed to merge: docker compose --env-file ${ENV_FILE} ${files[*]} config" >&2
    docker compose --env-file "${ENV_FILE}" "${files[@]}" config >/dev/null
    return 2
  fi
}

# Pre-compute the base-only service set once so we can detect what each
# overlay newly introduces (vs. merely modifies).
# Capture into a variable BEFORE the while-read instead of feeding via
# `done < <(...)` — process substitution runs in a subshell whose exit
# code is invisible to `set -e`, so a failed `service_report` would
# silently produce an empty loop. With `<<<` heredoc string + an explicit
# capture, any non-zero from service_report fails the script here.
if ! base_report=$(service_report "${BASE_COMPOSE}"); then
  echo "error: failed to read services from ${BASE_COMPOSE}" >&2
  exit 2
fi
declare -A is_base=()
while IFS=$'\t' read -r name _restart _nnp _capdrop; do
  [[ -z "${name}" ]] && continue
  is_base["${name}"]=1
done <<< "${base_report}"

if (( ${#is_base[@]} == 0 )); then
  echo "error: base compose has no services (or yq filter returned empty)" >&2
  exit 2
fi

offender_count=0

for overlay in "${overlays[@]}"; do
  if [[ ! -f "${overlay}" ]]; then
    echo "error: overlay file not found: ${overlay}" >&2
    exit 2
  fi

  rel_overlay="${overlay#"${REPO_ROOT}/"}"
  echo "==> checking ${rel_overlay}"

  introduced_count=0

  # Same reason as the base-report capture above — make service_report
  # failures fail the script visibly instead of producing an empty loop.
  if ! overlay_report=$(service_report "${BASE_COMPOSE}" "${overlay}"); then
    echo "error: failed to merge ${overlay} with ${BASE_COMPOSE}" >&2
    exit 2
  fi

  while IFS=$'\t' read -r name restart has_nnp has_capdrop_all; do
    [[ -z "${name}" ]] && continue

    # Skip services that already existed in the base compose — overlay
    # changes to existing services are out of scope (see header).
    if [[ -n "${is_base[${name}]+x}" ]]; then
      continue
    fi

    introduced_count=$((introduced_count + 1))

    # One-shot init containers (restart: "no") aren't part of the
    # long-running threat model. They're still allowed to harden
    # themselves (bugsink-init does), but we don't require it.
    if [[ "${restart}" == "no" ]]; then
      echo "    skip (one-shot): ${name}"
      continue
    fi

    missing=()
    [[ "${has_nnp}" == "true" ]] || missing+=("security_opt:[no-new-privileges:true]")
    [[ "${has_capdrop_all}" == "true" ]] || missing+=("cap_drop:[ALL]")

    if (( ${#missing[@]} == 0 )); then
      echo "    ok: ${name}"
      continue
    fi

    # Join with literal " AND " — IFS only takes the first char, so build
    # the message in a loop instead of relying on "${missing[*]}".
    reason="${missing[0]}"
    for (( i=1; i<${#missing[@]}; i++ )); do
      reason+=" AND ${missing[i]}"
    done
    echo "    FAIL: ${name}: missing ${reason}" >&2
    offender_count=$((offender_count + 1))
  done <<< "${overlay_report}"

  if (( introduced_count == 0 )); then
    echo "    no new services introduced — nothing to check"
  fi
done

if (( offender_count > 0 )); then
  cat >&2 <<EOF

Found ${offender_count} overlay service(s) without the stack's hardening
posture. Every long-running service an overlay introduces must declare:

  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL

(plus an explicit cap_add for whatever caps the workload actually needs).

Compose anchors don't cross file boundaries, so overlays must restate
the hardening — they cannot rely on an x- anchor from compose.yml. See
the existing app/web/worker/caddy/bugsink services for examples.
EOF
  exit 1
fi

echo "all overlays clean"
